#ifndef		DMA_CONFIG_H
#define 	DMA_CONFIG_H

//Enable or disable channels
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1			DISABLED
#define		DMA1_CHANNEL2			DISABLED
#define		DMA1_CHANNEL3			DISABLED
#define		DMA1_CHANNEL4			DISABLED
#define		DMA1_CHANNEL5			DISABLED
#define		DMA1_CHANNEL6			DISABLED
#define		DMA1_CHANNEL7			ENABLED
//Enable or disable Transfer complete interrupt
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1_TCIE		ENABLED
#define		DMA1_CHANNEL2_TCIE		ENABLED
#define		DMA1_CHANNEL3_TCIE		ENABLED
#define		DMA1_CHANNEL4_TCIE		ENABLED
#define		DMA1_CHANNEL5_TCIE		ENABLED
#define		DMA1_CHANNEL6_TCIE		ENABLED
#define		DMA1_CHANNEL7_TCIE		ENABLED
//Enable or disable Half transfer interrupt
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1_HTIE		DISABLED
#define		DMA1_CHANNEL2_HTIE		DISABLED
#define		DMA1_CHANNEL3_HTIE		DISABLED
#define		DMA1_CHANNEL4_HTIE		DISABLED
#define		DMA1_CHANNEL5_HTIE		DISABLED
#define		DMA1_CHANNEL6_HTIE		DISABLED
#define		DMA1_CHANNEL7_HTIE		DISABLED
//Enable or disable Transfer error interrupt
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1_TEIE		DISABLED
#define		DMA1_CHANNEL2_TEIE		DISABLED
#define		DMA1_CHANNEL3_TEIE		DISABLED
#define		DMA1_CHANNEL4_TEIE		DISABLED
#define		DMA1_CHANNEL5_TEIE		DISABLED
#define		DMA1_CHANNEL6_TEIE		DISABLED
#define		DMA1_CHANNEL7_TEIE		DISABLED
//Enable or disable Read from memory transfer direction
//options : { ENABLED, DISABLED }
//DISABLED: Reads from peripheral
#define		DMA1_CHANNEL1_DIR_MEM	DISABLED
#define		DMA1_CHANNEL2_DIR_MEM	DISABLED
#define		DMA1_CHANNEL3_DIR_MEM	DISABLED
#define		DMA1_CHANNEL4_DIR_MEM	DISABLED
#define		DMA1_CHANNEL5_DIR_MEM	DISABLED
#define		DMA1_CHANNEL6_DIR_MEM	DISABLED
#define		DMA1_CHANNEL7_DIR_MEM	DISABLED
//Enable or disable Circular mode
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1_CIRC		DISABLED
#define		DMA1_CHANNEL2_CIRC		DISABLED
#define		DMA1_CHANNEL3_CIRC		DISABLED
#define		DMA1_CHANNEL4_CIRC		DISABLED
#define		DMA1_CHANNEL5_CIRC		DISABLED
#define		DMA1_CHANNEL6_CIRC		DISABLED
#define		DMA1_CHANNEL7_CIRC		DISABLED
//Enable or disable Peripheral increment mode
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1_PINC		ENABLED
#define		DMA1_CHANNEL2_PINC		ENABLED
#define		DMA1_CHANNEL3_PINC		ENABLED
#define		DMA1_CHANNEL4_PINC		ENABLED
#define		DMA1_CHANNEL5_PINC		ENABLED
#define		DMA1_CHANNEL6_PINC		ENABLED
#define		DMA1_CHANNEL7_PINC		ENABLED
//Enable or disable Memory increment mode
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1_MINC		ENABLED
#define		DMA1_CHANNEL2_MINC		ENABLED
#define		DMA1_CHANNEL3_MINC		ENABLED
#define		DMA1_CHANNEL4_MINC		ENABLED
#define		DMA1_CHANNEL5_MINC		ENABLED
#define		DMA1_CHANNEL6_MINC		ENABLED
#define		DMA1_CHANNEL7_MINC		ENABLED
//Choose Peripheral size
//options : { SIZE_8BIT, SIZE_16BIT, SIZE_32BIT }
#define		DMA1_CHANNEL1_PSIZE		SIZE_32BIT
#define		DMA1_CHANNEL2_PSIZE		SIZE_32BIT
#define		DMA1_CHANNEL3_PSIZE		SIZE_32BIT
#define		DMA1_CHANNEL4_PSIZE		SIZE_32BIT
#define		DMA1_CHANNEL5_PSIZE		SIZE_32BIT
#define		DMA1_CHANNEL6_PSIZE		SIZE_32BIT
#define		DMA1_CHANNEL7_PSIZE		SIZE_32BIT
//Choose MEmory size
//options : { SIZE_8BIT, SIZE_16BIT, SIZE_32BIT }
#define		DMA1_CHANNEL1_MSIZE		SIZE_32BIT
#define		DMA1_CHANNEL2_MSIZE		SIZE_32BIT
#define		DMA1_CHANNEL3_MSIZE		SIZE_32BIT
#define		DMA1_CHANNEL4_MSIZE		SIZE_32BIT
#define		DMA1_CHANNEL5_MSIZE		SIZE_32BIT
#define		DMA1_CHANNEL6_MSIZE		SIZE_32BIT
#define		DMA1_CHANNEL7_MSIZE		SIZE_32BIT
//Choose Channel priority level
//options : { LOW_PRIORITY, MEDIUM_PRIORITY, HIGH_PRIORITY, VERYHIGH_PRIORITY }
#define		DMA1_CHANNEL1_PL		VERYHIGH_PRIORITY
#define		DMA1_CHANNEL2_PL		VERYHIGH_PRIORITY
#define		DMA1_CHANNEL3_PL		VERYHIGH_PRIORITY
#define		DMA1_CHANNEL4_PL		VERYHIGH_PRIORITY
#define		DMA1_CHANNEL5_PL		VERYHIGH_PRIORITY
#define		DMA1_CHANNEL6_PL		VERYHIGH_PRIORITY
#define		DMA1_CHANNEL7_PL		VERYHIGH_PRIORITY
//Enable or disable Memory to memory mode
//options : { ENABLED, DISABLED }
#define		DMA1_CHANNEL1_M2M		ENABLED
#define		DMA1_CHANNEL2_M2M		ENABLED
#define		DMA1_CHANNEL3_M2M		ENABLED
#define		DMA1_CHANNEL4_M2M		ENABLED
#define		DMA1_CHANNEL5_M2M		ENABLED
#define		DMA1_CHANNEL6_M2M		ENABLED
#define		DMA1_CHANNEL7_M2M		ENABLED


#endif
